### ISSUE TITLE
can't start autodj

### ISSUE THREAD

**Issue by duohost** [gaza1994/SHOUTcast-Manager#2]
I cant start autodj

**Comment by morrisond91** [comment]
I might be stating the obvious, but it may require shell access on the server.

Also i had a similar problem with SMI, another shoutcast manager. I had to re-download the Ices binary using ssh terminal via putty.

**Comment by gaza1994** [comment]
hi - yes this does appear to be an on going issue with the SHOUTcast binary - the best method i found was to download the tar.gz or ZIP of the binary wget that to your server then extract it into the correct location using your shell access.

that way all the permissions etc are correct when starting up the binary

you can also verify its working by doing /path/to/sc_serv /path/to/server-files/name.conf

**Comment by duohost** [comment]
Where can i download shoutcast binary and where to put it ?

**Comment by gaza1994** [comment]
shoutcast.com is the best place to get it from - make sure its version 2 that you download as the legacy one no longer works in modern browsers.

**Comment by gaza1994** [comment]
Please also double check the documentation: https://github.com/gaza1994/SHOUTcast-Manager/wiki to make sure everything has been installed correctly.
