### ISSUE TITLE
whmcs error

### ISSUE THREAD

**Issue by duohost** [gaza1994/SHOUTcast-Manager#3]
There is error in whmcs api plugin.
When i click on Login to SHOUTcast Control Panel i get to wrong link: http//panel.mydomain.com
Also command change password doesnt change password.
And server controler doenst work too.

**Comment by gaza1994** [comment]
You will need to check your module settings in WHMCS - as that is where we get the URL from.

For reference we use 

`{$smarty.server.HTTP_HOST}`

**Comment by gaza1994** [comment]
Please check the Wiki: https://github.com/gaza1994/SHOUTcast-Manager/wiki on how to setup the WHMCS plugin - i have just moved all the documentation from my website to here while my new site is unavailable

**Comment by djgaby7** [comment]
how can i download WHMCS plugin , website is dead
