### ISSUE TITLE
after Install just a blank Page

### ISSUE THREAD

**Issue by Makunia** [gaza1994/SHOUTcast-Manager#7]
Hey i have installed your Shoutcast-Manager on a Ubuntu 18.07 with PhP 7.2 complete down but now i just become a blank loginpage. :(  The log say, they have any issue with the mysql command (not anymore exist)

**Comment by gaza1994** [comment]
Can you check the php error log?

**Comment by Gelson62** [comment]
Hi gaza1994
I have installed Shoutcast-Manager without problems but when I log in as administrator I just only see a text base site. What is wrong or what is missing

**Comment by Gelson62** [comment]
2-Factor authentication is also not working because when I scan the QR code in Google Authenticator I received an error and it says that the QR code is invalid

**Comment by Danicgcr** [comment]
Hello, thank you very much for your incredible project, How can I start the shoutcast? I have not managed to do it, could you help me, Thanks.

**Comment by gareth-johnstone** [comment]
@Danicgcr normally when SHOUTcast doesn't start its normally relating to permissions of the SHOUTcast binary, try running it manually via command line and see if it starts there.

**Comment by gareth-johnstone** [comment]
@Gelson62 for your first problem there, try manually setting the URL in the MySQL database, it sounds like its missing it.

**Comment by Hightechteam** [comment]
![image](https://user-images.githubusercontent.com/19544153/47684651-f91a3380-dba9-11e8-98eb-ba092d67ecb4.png)

Seems to be an additional / for css and js files.

**Comment by Hightechteam** [comment]
![image](https://user-images.githubusercontent.com/19544153/47684743-544c2600-dbaa-11e8-8981-e2b57babe5eb.png)

**Comment by koertje12** [comment]
I try a new install to see this  fault  "   //   "

**Comment by koertje12** [comment]
Don't work, is see nothing in the error logs!!

**Comment by Loudgi** [comment]
34/5000
could you solve your problem?

**Comment by Hightechteam** [comment]
Yes, I went to template folders and changed the path to resources in the head like stylesheet etc.

**Comment by Loudgi** [comment]
Ok thanks @Hightechteam 
I'm going to dig deeper on the template folder side as well, to see if I solve this blank page problem at login
